import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)), pub=path.join(root,'public'), dbFile=path.join(root,'db.json');
const PORT=Number(process.env.PORT||3000), mock=String(process.env.MOCK_MODE||'true')!=='false';
let db={settings:{mockMode:mock},contacts:[{id:'c1',name:'Demo Customer',phone:'919999999999',labels:['new'],notes:'Local demo'}],labels:[{id:'new',name:'New Customer'},{id:'paid',name:'Paid'},{id:'vip',name:'VIP'},{id:'support',name:'Support'}],messages:[{id:'m1',contactId:'c1',direction:'in',type:'text',text:'Hi GAMAV!',timestamp:new Date().toISOString(),status:'read'},{id:'m2',contactId:'c1',direction:'out',type:'text',text:'Welcome to GAMAV WhatsApp 👋',timestamp:new Date().toISOString(),status:'delivered'}],bots:[{id:'b1',name:'Welcome Bot',enabled:true,trigger:'hi,hello,hey',nodes:[{id:'n1',type:'message',x:60,y:90,title:'Welcome',data:{text:'Welcome to GAMAV, {{customer_name}} 👋'}},{id:'n2',type:'buttons',x:360,y:90,title:'Main Menu',data:{text:'Choose an option',buttons:[{title:'Products',action:'reply',value:'products'},{title:'Support',action:'reply',value:'support'},{title:'Website',action:'url',value:'https://example.com'}]}}]}],templates:[{id:'t1',name:'order_update',category:'UTILITY',language:'en',status:'DRAFT',body:'Hi {{1}}, your order {{2}} is ready.'}],campaigns:[],logs:[]};
try{db=JSON.parse(fs.readFileSync(dbFile,'utf8'))}catch{fs.writeFileSync(dbFile,JSON.stringify(db,null,2))}
const save=()=>fs.writeFileSync(dbFile,JSON.stringify(db,null,2));
const json=(res,code,x)=>{res.writeHead(code,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(x))};
const read=async req=>new Promise(r=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{r(s?JSON.parse(s):{})}catch{r({})}})});
function contact(phone,name){let c=db.contacts.find(x=>x.phone===phone);if(!c){c={id:'c_'+crypto.randomUUID(),name:name||phone,phone,labels:['new'],notes:''};db.contacts.push(c)}return c}
function addMessage(c,d,type,payload,status='sent'){const m={id:'m_'+crypto.randomUUID(),contactId:c.id,direction:d,type,timestamp:new Date().toISOString(),status,...payload};db.messages.push(m);return m}
async function metaSend(p){const version=process.env.WHATSAPP_GRAPH_VERSION||'v23.0', id=process.env.WHATSAPP_PHONE_NUMBER_ID, token=process.env.WHATSAPP_ACCESS_TOKEN;if(!id||!token)throw Error('Meta credentials not configured');let body={messaging_product:'whatsapp',to:p.phone,type:p.type||'text'};if((p.type||'text')==='text')body.text={preview_url:true,body:p.text||''};else if(p.type==='image')body.image={link:p.imageUrl,caption:p.text||''};else if(p.type==='interactive')body.interactive={type:'button',body:{text:p.text||''},action:{buttons:(p.buttons||[]).slice(0,3).map((b,i)=>({type:'reply',reply:{id:'b'+i,title:String(b.title).slice(0,20)}}))}};else throw Error('Unsupported message type');const r=await fetch(`https://graph.facebook.com/${version}/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j?.error?.message||`Graph API ${r.status}`);return j}
const render=(s,c)=>String(s||'').replaceAll('{{customer_name}}',c.name||'').replaceAll('{{phone}}',c.phone||'');
async function send(p){const phone=String(p.phone||'').replace(/\D/g,'');if(!phone)throw Error('phone is required');const c=contact(phone,p.name);let provider='mock',response={id:'mock_'+crypto.randomUUID()};if(!db.settings.mockMode){provider='meta';response=await metaSend({...p,phone})}const m=addMessage(c,'out',p.type||'text',{text:p.text||'',imageUrl:p.imageUrl||'',buttons:p.buttons||[]},db.settings.mockMode?'delivered':'sent');save();return{ok:true,provider,response,message:m}}
async function bot(phone,text){const s=String(text||'').trim().toLowerCase();const c=contact(phone);for(const b of db.bots.filter(x=>x.enabled)){const keys=String(b.trigger).split(',').map(x=>x.trim().toLowerCase());if(!keys.includes(s))continue;for(const n of b.nodes||[]){if(n.type==='message')await send({phone,type:'text',text:render(n.data?.text,c)});if(n.type==='image')await send({phone,type:'image',imageUrl:n.data?.imageUrl,text:render(n.data?.caption,c)});if(n.type==='buttons')await send({phone,type:'interactive',text:render(n.data?.text,c),buttons:n.data?.buttons||[]})}return b.id}return null}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');const p=u.pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});return res.end()}
if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,mode:db.settings.mockMode?'mock':'meta'});
if(req.method==='GET'&&p==='/api/state')return json(res,200,db);
if(req.method==='GET'&&p==='/api/contacts')return json(res,200,db.contacts);
if(req.method==='GET'&&p==='/api/messages')return json(res,200,db.messages.filter(m=>!u.searchParams.get('contactId')||m.contactId===u.searchParams.get('contactId')));
if(req.method==='GET'&&p==='/api/bots')return json(res,200,db.bots);
if(req.method==='GET'&&p==='/api/labels')return json(res,200,db.labels);
if(req.method==='GET'&&p==='/api/templates')return json(res,200,db.templates);
if(req.method==='POST'&&p==='/api/messages/send')return json(res,200,await send(await read(req)));
if(req.method==='POST'&&p==='/api/simulate/inbound'){const x=await read(req),c=contact(String(x.phone).replace(/\D/g,''),x.name);const m=addMessage(c,'in',x.type||'text',{text:x.text||''},'read');save();const botId=await bot(c.phone,x.text);return json(res,200,{ok:true,message:m,botId})}
if(req.method==='POST'&&p==='/api/bots'){const x=await read(req),b={id:'b_'+crypto.randomUUID(),name:x.name||'New Bot',enabled:x.enabled!==false,trigger:x.trigger||'',nodes:x.nodes||[],edges:x.edges||[]};db.bots.push(b);save();return json(res,201,b)}
if(req.method==='PUT'&&p.startsWith('/api/bots/')){const id=p.split('/').pop(),x=await read(req),i=db.bots.findIndex(b=>b.id===id);if(i<0)return json(res,404,{error:'not found'});db.bots[i]={...db.bots[i],...x};save();return json(res,200,db.bots[i])}
if(req.method==='POST'&&p==='/api/labels'){const x=await read(req),l={id:'l_'+crypto.randomUUID(),name:x.name||'New Label'};db.labels.push(l);save();return json(res,201,l)}
if(req.method==='POST'&&p==='/api/campaigns'){const x=await read(req),c={id:'cmp_'+crypto.randomUUID(),createdAt:new Date().toISOString(),status:'draft',...x};db.campaigns.push(c);save();return json(res,201,c)}
if(req.method==='POST'&&p==='/api/settings'){db.settings={...db.settings,...await read(req)};save();return json(res,200,db.settings)}
if(req.method==='GET'&&p==='/webhook/whatsapp'){const mode=u.searchParams.get('hub.mode'),token=u.searchParams.get('hub.verify_token'),ch=u.searchParams.get('hub.challenge');if(mode==='subscribe'&&token===(process.env.WHATSAPP_VERIFY_TOKEN||'')){res.writeHead(200,{'Content-Type':'text/plain'});return res.end(ch||'')}return json(res,403,{error:'verification failed'})}
if(req.method==='POST'&&p==='/webhook/whatsapp'){const x=await read(req);db.logs.push({id:'w_'+crypto.randomUUID(),timestamp:new Date().toISOString(),payload:x});save();try{const v=x?.entry?.[0]?.changes?.[0]?.value,m=v?.messages?.[0],ct=v?.contacts?.[0];if(m?.from){const c=contact(m.from,ct?.profile?.name||m.from),t=m?.text?.body||'';addMessage(c,'in',m.type||'unknown',{text:t},'received');save();if(t)await bot(m.from,t)}}catch{}return json(res,200,{received:true})}
let file=p==='/'?'index.html':p.replace(/^\/+/,''),fp=path.join(pub,path.normalize(file));if(fp.startsWith(pub)&&fs.existsSync(fp)&&fs.statSync(fp).isFile()){res.writeHead(200,{'Content-Type':file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html'});return res.end(fs.readFileSync(fp))}return json(res,404,{error:'not found'});}catch(e){console.error(e);json(res,500,{error:e.message})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`GAMAV WhatsApp: http://127.0.0.1:${PORT}`));
